### ISSUE TITLE
Add time command to free version

### ISSUE THREAD

**Issue by coderGtm** [coderGtm/yantra-app-launcher#118]
The time command is a very handy command and imo should be available in the free version also.

This is a very easy task. Good opportunity for someone wanting to make their first open source code contribution!

Other contributors are welcome as well!

**Comment by Anshu-Bijarnia** [comment]
I would like to give this a try.

**Comment by coderGtm** [comment]
Go ahead!

**Comment by coderGtm** [comment]
Any progress?

**Comment by Anshu-Bijarnia** [comment]
I will look into this today, can you give me till the end of the day ?

**Comment by coderGtm** [comment]
Closing with #120
