### ISSUE TITLE
bottom prompt and scroll up ui

### ISSUE THREAD

**Issue by scientiac** [coderGtm/yantra-app-launcher#134]
ability to keep the prompt at the botton, just above the suggestion strip (always above keyboard) and when the results are printed it goes up instead of coming down, eliminating the need of scrolling down because, currently while using commands the printed outputs go below the keyboard and there is a need to scroll up

similar to how warp terminal handles the commands output (prompt at the bottom scrolling up results)

https://www.youtube.com/watch?v=34INSNevPOk

**Comment by coderGtm** [comment]
Definitely needed! Although I was not able to get it to work last time I tried. Can you try it?

**Comment by coderGtm** [comment]
Done: 81aeeda
