### ISSUE TITLE
Spelling mistake in Crash message

### ISSUE THREAD

**Issue by coderGtm** [coderGtm/yantra-app-launcher#136]
![Screenshot_20240602_183224_Yantra_Launcher.jpg](https://github.com/coderGtm/yantra-app-launcher/assets/66418526/ac3757b0-4094-4169-8595-f90fce2af2b5)

**Comment by AnirudhSingal** [comment]
@coderGtm IM interested in working on this.

**Comment by coderGtm** [comment]
Please go ahead!

**Comment by coderGtm** [comment]
Hi! Are you doing this one?

**Comment by coderGtm** [comment]
Okay! I'd be doing it myself in a few hours. If anyone is interested, they can patch this by then.

**Comment by coderGtm** [comment]
Fixed with 048a04fe0de82ca890e80977c1f829507beeae73
