### ISSUE TITLE
Contributor commands

### ISSUE THREAD

**Issue by coderGtm** [coderGtm/yantra-app-launcher#137]
This issue is created to add all the contributors till now to the contributors section using the [all-contributors Bot](https://github.com/all-contributors/app)

See [usage](https://allcontributors.org/docs/en/bot/usage) for commands.

**Comment by coderGtm** [comment]
@all-contributors please add @coderGtm for code

**Comment by coderGtm** [comment]
@all-contributors
please add @coderGtm for doc
please add @coderGtm for design
please add @coderGtm for ideas
please add @coderGtm for maintenance
please add @coderGtm for projectManagement
please add @coderGtm for research
please add @coderGtm for review

**Comment by coderGtm** [comment]
https://github.com/all-contributors
please add @coderGtm for doc.
please add @coderGtm for design.
please add @coderGtm for ideas.
please add @coderGtm for maintenance.
please add @coderGtm for projectManagement.
please add @coderGtm for research.
please add @coderGtm for review.

**Comment by coderGtm** [comment]
@all-contributors
please add @coderGtm for doc.
please add @coderGtm for design.
please add @coderGtm for ideas.
please add @coderGtm for maintenance.
please add @coderGtm for projectManagement.
please add @coderGtm for research.
please add @coderGtm for review.

**Comment by coderGtm** [comment]
@all-contributors
please add @coderGtm for doc.
please add @coderGtm for design.
please add @coderGtm for ideas.
please add @coderGtm for maintenance.
please add @coderGtm for projectManagement.
please add @coderGtm for research.

**Comment by coderGtm** [comment]
@all-contributors please add @coderGtm for doc.
@all-contributors please add @coderGtm for design.
@all-contributors please add @coderGtm for ideas.
@all-contributors please add @coderGtm for maintenance.
@all-contributors please add @coderGtm for projectManagement.

**Comment by coderGtm** [comment]
@all-contributors please add @coderGtm for doc.

**Comment by coderGtm** [comment]
@all-contributors please add @coderGtm for design.

**Comment by coderGtm** [comment]
@all-contributors please add @coderGtm for ideas.

**Comment by coderGtm** [comment]
@all-contributors please add @coderGtm for maintenance.

**Comment by axolotl-git** [comment]
@all-contributors please add @axolotl-git  for translation

**Comment by Anready** [comment]
@all-contributors please add @Anready for code

**Comment by Anready** [comment]
@all-contributors please add @Anready for translation

**Comment by coderGtm** [comment]
closing now as not needed
