### ISSUE TITLE
[anything else] 

### ISSUE THREAD

**Issue by Playgirlkaybraz11** [coderGtm/yantra-app-launcher#172]
I would like to request the following command for Yantra Launcher:

[COMMAND]

[DESCRIPTION]

[EXAMPLE]

[ANYTHING ELSE]

**Comment by Anready** [comment]
Seriously??? @coderGtm can you close issue and ban somehow this person

**Comment by coderGtm** [comment]
Done

**Comment by Qutition** [comment]
> I would like to request the following command for Yantra Launcher:
> 
> [COMMAND]
> 
> [DESCRIPTION]
> 
> [EXAMPLE]
> 
> [ANYTHING ELSE]

💀
