### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by AndrewAmbrosio** [coderGtm/yantra-app-launcher#173]
I would like to request the following command for Yantra Launcher:

[COMMAND]
Wallpaper
[DESCRIPTION]
I would like the launcher to allow changing the background wallpaper, instead of being just dark
[EXAMPLE]
To allow setting my own wallpapers, would be great
[ANYTHING ELSE]

**Comment by Anready** [comment]
@coderGtm i think this is again spam
