### ISSUE TITLE
Cd, ls, open and pwd not work on android 12

### ISSUE THREAD

**Issue by Anready** [coderGtm/yantra-app-launcher#176]
**Describe the bug**
I can't use this commands on android 12, but on my another phone with android 7 all is okay

**To Reproduce**
1. On android 12 write one of this commands

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 12 Pro
 - OS: 12
 - Version last

**Additional context**
 I think you need to approve pull request #175

**Comment by coderGtm** [comment]
Ik you made a pr 😂

**Comment by Anready** [comment]
thanks for solving
