### ISSUE TITLE
Auto Execute Command on Startup 

### ISSUE THREAD

**Issue by manuthr** [coderGtm/yantra-app-launcher#178]
I would like to request the following command for Yantra Launcher:

[AutoExecute]

[If the command is to Execute sysinfo -art command, Execute the following command automatically whenever the screen on/cli loads, in order to display the relavent ascii art on top.]

[Auto Execute Command : sysinfo -art

Execute : Yantra Launcher (v9.7) on Xiaomi M2010J19CG

$user > sysinfo -art

_nnnn_                      
        dGGGGMMb     ,"""""""""""""".
       @p~qp~~qMb    | Linux Rules! |
       M|@||@) M|   _;..............'
       @,----.JM| -'
      JS^\__/  qKL
     dZP        qKRb
    dZP          qKKb
   fZP            SMMb
   HZM            MMMM
   FqM            MMMM
 __| ".        |\dS"qML
 |    `.       | `' \Zq
_)      \.___.,|     .'
\____   )MMMMMM|   .'
     `-'       `--' hjm

]

[This is more like a feature, not a command..As same as Command to Execute on double Tap]

**Comment by coderGtm** [comment]
This feature is already available as the `init` command. Although that command is limited to the Pro version of the app.
