### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by AjaySaklani0** [coderGtm/yantra-app-launcher#182]
I would like to request the following command for Yantra Launcher:

[COMMAND]

[DESCRIPTION]
You can add shortcut commands for opening apps like fb for Facebook, yt for YouTube and other that you think.
[EXAMPLE]

[ANYTHING ELSE]

**Comment by Anready** [comment]
What the hell? "alias" command: alias yt = launch youtube, alias yt = youtube. I just don’t understand why spam? And if this is really a question, which I highly doubt, then before creating issues on GitHub: a) read the 'help' command, b) write to the community on discord if 'a' not helped. @coderGtm ban?

**Comment by coderGtm** [comment]
Cool down bro 😄

**Comment by coderGtm** [comment]
@AjaySaklani0 did you check the alias command?

**Comment by Anready** [comment]
@AjaySaklani0 If you don’t respond to a comment from gtm within 24 hours, you will receive a ban and a report

**Comment by coderGtm** [comment]
He's kidding

**Comment by AjaySaklani0** [comment]
I am using this launcher from two days so I don't understand some features, now I checked alias command,that exactly what I want

**Comment by Anready** [comment]
> I am using this launcher from two days so I don't understand some features, now I checked alias command,that exactly what I want 

forgive me, I thought you were another spammer, my apologies

**Comment by Anready** [comment]
> I am using this launcher from two days so I don't understand some features, now I checked alias command,that exactly what I want 

forgive me, I thought you were another spammer, my apologies
