### ISSUE TITLE
Set to default launcher command

### ISSUE THREAD

**Issue by Qutition** [coderGtm/yantra-app-launcher#187]
I would like to request the following command for Yantra Launcher:

[COMMAND] - setup

[DESCRIPTION] - Makes the launcher the default one

[EXAMPLE] - setup

[ANYTHING ELSE] - e

**Comment by coderGtm** [comment]
Will keep this in mind to have this option somewhere, not necessarily as a
command.

**Comment by coderGtm** [comment]
It's not a new command but an enhancement to the launcher experience so...

**Comment by coderGtm** [comment]
Implemented as a settings option!

**Comment by Qutition** [comment]
@coderGtm you made it only in pro?

**Comment by coderGtm** [comment]
Nope. It'd be available in both versions.
