### ISSUE TITLE
uninstall -p argument

### ISSUE THREAD

**Issue by Qutition** [coderGtm/yantra-app-launcher#188]
I would like to request the following command for Yantra Launcher:

[COMMAND] uninstall (u)

[DESCRIPTION] Deletes app by its package name

[EXAMPLE] uninstall -p com.delete.me / u -p com.delete.me

[ANYTHING ELSE] - maybe add -s argument but idk how it will work. (-s argument from launch command)

**Comment by coderGtm** [comment]
Firstly, the uninstall command is intentionally kept a little tedious to prevent (or rather minimize) accidental data loss. Secondly, the -s flag is for shortcuts that other apps publish. So if the base app is uninstalled, those shortcuts get removed automatically.

**Comment by Qutition** [comment]
> Firstly, the uninstall command is intentionally kept a little tedious to prevent (or rather minimize) accidental data loss. Secondly, the -s flag is for shortcuts that other apps publish. So if the base app is uninstalled, those shortcuts get removed automatically.

Anyways it gives you system confirmation and you cant just u -p very.important.app andbits instantly deletes

And actually you can add a terminal confirmation, like **"Do you like do delete this [APP]? [y/N]:"** Default is No

**Comment by Qutition** [comment]
> > And actually you can add a terminal confirmation, like "Do you like do delete this [APP]? [y/N]:" Default is No
> 
> launcher dosen't support this as much as ik

Oh, that's sad. Anyways I'll try to fork the repo and try.
