### ISSUE TITLE
echo command

### ISSUE THREAD

**Issue by Qutition** [coderGtm/yantra-app-launcher#194]
I would like to request the following command for Yantra Launcher:

[COMMAND] echo (text)

[DESCRIPTION] Prints text to termin

[EXAMPLE] echo Hello World!

[ANYTHING ELSE] - e

**Comment by axolotl-git** [comment]
This command already exists, Before making a request please check the available commands using `help` in the Launcher

**Comment by Qutition** [comment]
> This command already exists, Before making a request please check the available commands using `help` in the Launcher 

its only pro version thing, I don't see it in a free one

**Comment by Anready** [comment]
yes, only in pro
