### ISSUE TITLE
crash alias

### ISSUE THREAD

**Issue by Qutition** [coderGtm/yantra-app-launcher#195]
**Smartphone (please complete the following information):**
 - Device: [HONOR X9b 5G 256GB]
 - OS: [MagicOS 8.0 Android 14]
 - Version [9.7]

**Additional context**
a = alias
also if you give it any name it doesn't care, like alias rrr = rrr crashes too
the funny part that after that I goet referred to original HONOR launcher, but when I just click home i.go back to Yantra-app-launcher

**Comment by Qutition** [comment]
https://github.com/user-attachments/assets/17fe1e0f-410f-4c89-a6de-9a9b5deac43e

heres

**Comment by coderGtm** [comment]
Damn that's bad! Thanks for reporting it. Will fix this 👍

**Comment by Anready** [comment]
> lv_0_20240904140838.mp4 
> heres

lol this is a very brilliant idea how to crash launcher (ты гений and tester)

**Comment by coderGtm** [comment]
Fixed by c2b0e0a
Thanks once again for reporting!
