### ISSUE TITLE
worse than a bug 

### ISSUE THREAD

**Issue by Qutition** [coderGtm/yantra-app-launcher#197]
SO ANNOYING, I WANNA SEE MY COMMAND WHY THE SUGGESTIONS BAR OVERLAINGN IT???? +why there are two of -p and -s arguments

https://github.com/user-attachments/assets/0783755d-ee39-43e7-9b81-f9ae3076f003

honor x9b 5g 256gb
MagicOS 8.0 Android 14
9.7

**Comment by Anready** [comment]
@coderGtm I have no idea how to debug this and see what's wrong

**Comment by Anready** [comment]
@coderGtm I have no idea how to debug this and see what's wrong

**Comment by Qutition** [comment]
pwease firstly fix suggestions bar @Anready

**Comment by Anready** [comment]
> pwease firstly fix suggestions bar @Anready

i mean that we need to find whats wrong with suggestion bar before fixing :)

**Comment by Qutition** [comment]
> > pwease firstly fix suggestions bar @Anready
> 
> i mean that we need to find whats wrong with suggestion bar before fixing :)

ok

**Comment by coderGtm** [comment]
This is related to the issue regarding scrolling.

**Comment by coderGtm** [comment]
Solved
