### ISSUE TITLE
Add Screen Time command

### ISSUE THREAD

**Issue by prakhargaming** [coderGtm/yantra-app-launcher#200]
I would like to request the following command for Yantra Launcher:

[COMMAND]: stime (screen time)

[DESCRIPTION]: a command that lists the amount of screen on time since the start of the day.

[EXAMPLE]: 
$root: stime
The amount of screen time today is 3 hr 5 min
$root: 

[ANYTHING ELSE]: nothing

**Comment by coderGtm** [comment]
There is already a `screentime` command in the Pro version of the app.
