### ISSUE TITLE
This is a damn good app

### ISSUE THREAD

**Issue by hopen-hub** [coderGtm/yantra-app-launcher#205]
I would like to request the following command for Yantra Launcher:

[COMMAND]
I think you can add some classic unix commends like apt cd pkg install 
[DESCRIPTION]
Do you think so
[EXAMPLE]
apt ls pkg 
[ANYTHING ELSE]
Thank you

**Comment by Anready** [comment]
cd already exist (also ls, pwd and open)

**Comment by coderGtm** [comment]
Those were temporarily disabled but will be available again from the next update.
