### ISSUE TITLE
Great app

### ISSUE THREAD

**Issue by hopen-hub** [coderGtm/yantra-app-launcher#206]
hi there ,this is a real cool app, I think you can add more unix commands like apt intstall or pkg,,,, and add editors like vim or nvim ,

I think you can make it like a real terminal that can also control your phone.

I know it's kinds of hard but that'll be really much cooler .

**Comment by axolotl-git** [comment]
Hey! Currently this Launcher is not able to do these, but Yantra Launcher has an integration with Termux! You can do some things with this integration

If you want to know more and maybe get answers from more people and faster you can join the discord server to maybe discuss it better

**Comment by axolotl-git** [comment]
Hey! Currently this Launcher is not able to do these, but Yantra Launcher has an integration with Termux! You can do some things with this integration

If you want to know more and maybe get answers from more people and faster you can join the discord server to maybe discuss it better

**Comment by coderGtm** [comment]
Well-explained by @axolotl-git
