### ISSUE TITLE
Always open keyboard setting

### ISSUE THREAD

**Issue by disco-volante** [coderGtm/yantra-app-launcher#216]
There could be an option to have the keyboard always open in the launcher since the majority of interactions with the happen through text commands.

**Comment by coderGtm** [comment]
Keyboard will obstruct half of the already limited space on mobile devices. Although there is a switch in Yantra Launcher settings that makes it not hide keyboard on command enter. Besides, you can always tap on the terminal to quickly open up the keyboard.

**Comment by disco-volante** [comment]
> Keyboard will obstruct half of the already limited space on mobile devices. Although there is a switch in Yantra Launcher settings that makes it not hide keyboard on command enter. Besides, you can always tap on the terminal to quickly open up the keyboard.

From my point of view keyboard here is the main way to interact, so should be possible to have it always accessible. Also there's weird behaviour (at least on my One Plus 7t, will double check on pixel next week) that when exiting app via swipe gesture from the bottom, keyboard opens then is dismissed automatically after a second which makes the screen content shift back and forth.

**Comment by coderGtm** [comment]
Did you check the settings? There is indeed a way to keep it open as long as possible.

Can you share a minimal setup backup to reproduce the issue? I'll also check on my end.

**Comment by disco-volante** [comment]
> Did you check the settings? There is indeed a way to keep it open as long as possible.
> 
> Can you share a minimal setup backup to reproduce the issue? I'll also check on my end.

I don't see an option to make the keyboard appear initially (on enter). It starts hidden. The only option I see is "hide keyboard on command enter" which is disabled for me and works correctly. But would be cool to have it open initially so that I can start typing the command instantly.
I might have explained my first post better. "Always open" is misleading. It should read - an option to make keyboard appear open by default on Tantra Launcher focus. Other interactions would stay the same i.e. dismissing the keyboard via setting or user action.

How do I do a minimal setup backup on full version? If backup have no sensitive info I can attach it. I don't know the coding so can't verify the yantra file contents 😉

**Comment by coderGtm** [comment]
Ok this might be device specific. When I go back to home screen, my keyboard opens up instantly. That is the intended behaviour. I misunderstood your post previously due to the title as you pointed out.

The issue you described about keyboard showing and hiding back means that Yantra Launcher tried to open the keyboard but something closed it back. I don't have a one plus device to test it though.

**Comment by disco-volante** [comment]
> Ok this might be device specific. When I go back to home screen, my keyboard opens up instantly. That is the intended behaviour. I misunderstood your post previously due to the title as you pointed out.
> 
> The issue you described about keyboard showing and hiding back means that Yantra Launcher tried to open the keyboard but something closed it back. I don't have a one plus device to test it though.

Oooooh. Ok. So it starts open. You can see the video how it behaves on my device. No problem for me as I'm upgrading soon.

https://github.com/user-attachments/assets/710f7763-5582-4040-b3ba-ed4bbda2e869

P.s. thanks for this launcher. I had no idea such things existed. Bought a full version within minutes 🙃.

**Comment by axolotl-git** [comment]
On my device, Motorola e13, when Yantra Launcher opens the keyboard opens automatically, so as GTM already said I suspect it is a problem specific to your phone

**Comment by axolotl-git** [comment]
On my device, Motorola e13, when Yantra Launcher opens the keyboard opens automatically, so as GTM already said I suspect it is a problem specific to your phone

**Comment by disco-volante** [comment]
> On my device, Motorola e13, when Yantra Launcher opens the keyboard opens automatically, so as GTM already said I suspect it is a problem specific to your phone

Sure. Thanks.

**Comment by coderGtm** [comment]
Seeing the video, i am sure something is hindering the keyboard. I wish to solve it but would need to wait till I can get access to a OnePlus device for testing. Also, if you are interested, you may try to resolve it and open a pr.

Glad to know you liked the launcher. And yeah, upgrading from OnePlus is a good decision 🙂
