### ISSUE TITLE
Screen does not roll to the top

### ISSUE THREAD

**Issue by disco-volante** [coderGtm/yantra-app-launcher#220]
**Describe the bug**
Pixel 8. Android 14.
When entering launcher by swiping up from an app, keyboard opens but the screen does not roll to the top and the current prompt is not visible. 

![Screenshot_20240924-142644](https://github.com/user-attachments/assets/24c594b6-9a4e-4d6f-868d-6c1ebf43aee2)

**To Reproduce**
1. Open any app
2. Go home by swiping up

**Expected behavior**
Screen should automatically scroll up to reveal a prompt. Also every time the prompt is hidden and user starts typing, screen should roll up and reveal a prompt, like it does in standard terminal emulator.

**Smartphone (please complete the following information):**
 - Device: pixel 8
 - OS: android
 - Version 14

**Comment by coderGtm** [comment]
Tal the screen once to reveal the prompt. And I like the idea of going to the prompt as soon as typing starts. I'll configure it that way 👍🏻

**Comment by coderGtm** [comment]
Done long back 81aeeda9b6ca2a009731d808af3d66049e11096a
