### ISSUE TITLE
Swipe up from bottom action

### ISSUE THREAD

**Issue by disco-volante** [coderGtm/yantra-app-launcher#225]
Currently the "swipe up from bottom "action that in default launcher opens app drawer is not used and only blinks the screen. 

This could maybe open a panel/drawer with clickable aliases (with user assignable icons?) as the current bar is good for suggestions but not that convenient for browsing and selecting and item from the entire list.
The other options is maybe a panel with clickable history items or maybe anything else that might be usable.

**Comment by coderGtm** [comment]
I exactly understood the behaviour you are describing and even the idea is nice. But I doubt that that blink appears on all phones. I recently switched my device and only noticed it in the newer device

**Comment by coderGtm** [comment]
Can anyone else confirm?
