### ISSUE TITLE
Bug in the "flash" command using the new toggle function

### ISSUE THREAD

**Issue by marco-tuzza** [coderGtm/yantra-app-launcher#40]
Hi guys,

I don't know if I'm the only one with this problem but whenever I use the `flash` command without any argument the toggle act strange, make it impossible to use.

Here's a detail of what happens:

At the initial state my flashlight is **OFF**:
![first-step](https://github.com/coderGtm/yantra-app-launcher/assets/62022949/7a8a31ec-5edf-4f09-aa40-18f58b40b09a)

Now I launch the `flash` command without any argument, my flashlight is now **ON** and this is the output:
![second-step](https://github.com/coderGtm/yantra-app-launcher/assets/62022949/4aca39df-c70c-4b83-b040-98c6f27eea31)

And to finish I launch again the `flash` command without any argument, my flashlight is still **ON** and this is the output:
![third step](https://github.com/coderGtm/yantra-app-launcher/assets/62022949/2a9b8e31-0f28-4280-b377-53b26ab2667f)

I tested the command with **every single argument** and it works perfectly fine.

For more context: I run Yantra v9.0 on a Fairphone 4 with Android 13.

**Comment by coderGtm** [comment]
Although it doesn't happen on my device, I kind of know what broke on your device. I'll try to fix this.

**Comment by Anready** [comment]
Strange, everything is fine on my device

**Comment by coderGtm** [comment]
Does it still happen?
