### ISSUE TITLE
(REQ) Yantra launcher Turkish Translation

### ISSUE THREAD

**Issue by Vylesh** [coderGtm/yantra-app-launcher#91]
I Wanted Translate Launcher for Turkish Language
I will Looking your Return

**Comment by Anready** [comment]
why not? you can do translation, but i think u need to join to our discord to get instructions

**Comment by Vylesh** [comment]
> why not? you can do translation, but i think u need to join to our discord to get instructions

I'm Already At Discord with same name.

**Comment by Vylesh** [comment]
I pinged you on General Chat

**Comment by coderGtm** [comment]
Details have been shared in the community. Closing this now!
